#librerias

library(readxl)
library(readr)
library(summarytools)
library(rgdal)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(shiny)   # for web applications
library(stringi)
library(stringr)
library(phonics)
library(foreign)
library(knitr)
library(kableExtra)
library(phonics)
library(foreign)
library(data.table)
library(summarytools)